_meta_: {}
bundle_root: /content/drive/MyDrive/mmwhs2017/auto3dseg/segresnet_0
ckpt_path: $@bundle_root + '/model'
mlflow_tracking_uri: $@ckpt_path + '/mlruns/'
mlflow_experiment_name: Auto3DSeg
data_file_base_dir: /content/drive/MyDrive/data
data_list_file_path: /content/drive/MyDrive/mmwhs2017/auto3dseg/datalist.json
modality: ct
fold: 0
input_channels: 1
output_classes: 8
class_names: null
class_index: null
debug: false
ckpt_save: true
cache_rate: null
roi_size: [224, 224, 144]
auto_scale_allowed: true
auto_scale_batch: true
auto_scale_roi: false
auto_scale_filters: false
quick: false
channels_last: true
validate_final_original_res: true
calc_val_loss: false
amp: true
log_output_file: null
cache_class_indices: null
early_stopping_fraction: 0.001
determ: false
orientation_ras: true
crop_foreground: true
learning_rate: 0.0002
batch_size: 1
num_images_per_batch: 1
num_epochs: 1250
num_warmup_epochs: 3
sigmoid: false
resample: false
resample_resolution: [0.4384765028953552, 0.4384765028953552, 0.44999998807907104]
crop_mode: ratio
normalize_mode: range
intensity_bounds: [-11.25, 570.0]
num_epochs_per_validation: null
num_epochs_per_saving: 1
num_workers: 4
num_steps_per_image: null
num_crops_per_image: 5
loss: {_target_: DiceCELoss, include_background: true, squared_pred: true, smooth_nr: 0,
  smooth_dr: 1.0e-05, softmax: $not @sigmoid, sigmoid: $@sigmoid, to_onehot_y: $not
    @sigmoid}
optimizer: {_target_: torch.optim.AdamW, lr: '@learning_rate', weight_decay: 1.0e-05}
network:
  _target_: SegResNetDS
  init_filters: 32
  blocks_down: [1, 2, 2, 4, 4]
  norm: INSTANCE_NVFUSER
  in_channels: '@input_channels'
  out_channels: '@output_classes'
  dsdepth: 4
finetune: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt'}
validate: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_validation', save_mask: false, invert: true}
infer: {enabled: false, ckpt_name: $@bundle_root + '/model/model.pt', output_path: $@bundle_root
    + '/prediction_' + @infer#data_list_key, data_list_key: testing}
anisotropic_scales: false
spacing_median: [0.4384765028953552, 0.4384765028953552, 0.625]
spacing_lower: [0.283291015625, 0.283291015625, 0.44999998807907104]
spacing_upper: [0.5838969045877457, 0.5838969045877457, 0.625]
image_size_mm_median: [224.49996948242188, 224.49996948242188, 150.86249801516533]
image_size_mm_90: [261.99982910156257, 261.99982910156257, 183.375]
image_size: [597, 597, 407]
