_meta_: {}
image_key: image
label_key: label
transforms_validate:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    image_only: true
    keys: ['@image_key', '@label_key']
  - _target_: EnsureChannelFirstd
    keys: ['@image_key', '@label_key']
  - _target_: Compose
    transforms:
    - {_target_: ScaleIntensityRanged, a_max: 570.0, a_min: -11.25, b_max: 1.0, b_min: 0.0,
      clip: true, keys: '@image_key'}
    - _target_: CropForegroundd
      allow_smaller: true
      end_coord_key: null
      keys: ['@image_key', '@label_key']
      source_key: '@image_key'
      start_coord_key: null
  - _target_: Orientationd
    axcodes: RAS
    keys: ['@image_key', '@label_key']
  - _target_: Spacingd
    align_corners: [true, true]
    keys: ['@image_key', '@label_key']
    mode: [bilinear, nearest]
    pixdim: $@transforms#resample_resolution
  - _target_: CastToTyped
    dtype: [$torch.float32, $torch.uint8]
    keys: ['@image_key', '@label_key']
  - _target_: EnsureTyped
    keys: ['@image_key', '@label_key']
    track_meta: true
